# Generated by Django 2.2.4 on 2021-05-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('network', models.CharField(max_length=45)),
                ('release_date', models.DateTimeField()),
                ('descrption', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='dojo',
        ),
    ]
