# Generated by Django 2.2.4 on 2021-05-09 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20210509_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='descrption',
            new_name='description',
        ),
    ]
