# Generated by Django 2.2.4 on 2021-05-15 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_shows_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shows',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
