# Generated by Django 2.2.4 on 2021-05-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_auto_20210515_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
